version: '3.8'
services:
  api:
    build:
      context: ../
      dockerfile: infra/Dockerfile.api
    ports:
      - "8000:8000"
  app:
    build:
      context: ../
      dockerfile: infra/Dockerfile.app
    ports:
      - "7860:7860"
  worker:
    build:
      context: ../
      dockerfile: infra/Dockerfile.worker
